# Generated by Django 2.2.4 on 2019-08-17 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_on', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.CharField(blank=True, max_length=64)),
                ('num_answered', models.IntegerField(blank=True)),
                ('num_questions', models.IntegerField(blank=True)),
                ('num_correct', models.IntegerField(blank=True)),
                ('is_evaluated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('descripton', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcom_file', models.FileField(upload_to='dcom_files')),
                ('ans_type', models.IntegerField(choices=[(1, 'Normal'), (2, 'Abnormal')], default=1)),
                ('ans_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_type', models.IntegerField(choices=[(1, 'Normal'), (2, 'Abnormal')], default=1)),
                ('ans_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.AttemptedSet')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.Set'),
        ),
        migrations.AddField(
            model_name='attemptedset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.Set'),
        ),
        migrations.AddField(
            model_name='attemptedset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
