# Generated by Django 2.2.4 on 2019-08-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='descripton',
            new_name='description',
        ),
    ]
