# Generated by Django 2.2.4 on 2019-08-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0002_auto_20190817_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedset',
            name='num_answered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attemptedset',
            name='num_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attemptedset',
            name='num_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='ans_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
